### ISSUE TITLE
模板提供的 button 的 click 事件不生效

### ISSUE THREAD

**Issue by hqweay** [siyuan-note/plugin-sample-vite-svelte#31]
感谢作者的模板，开发效率 ++。

如 https://github.com/siyuan-note/plugin-sample-vite-svelte/blob/main/src/setting-example.svelte 中的用法，使用

```
{
            type: 'button',
            title: 'text',
            description: 'This is a text',
            ...
        },
```
时 click 事件好像没生效。我不大懂 svelte 语法，但 `setting-item.svelte` 里改为 click 后生效了。这里是不是写错了。

<img width="890" alt="image" src="https://github.com/siyuan-note/plugin-sample-vite-svelte/assets/23608642/fad951bd-544e-42c3-b11c-d5d27c34dfd1">

**Comment by frostime** [comment]
确实是 bug，我待会修复一下。

**Comment by frostime** [comment]
修复之后，可以通过 json object，独立定义 button 的 callback

![image](https://github.com/siyuan-note/plugin-sample-vite-svelte/assets/27268127/9d6cb697-cbf0-45ce-883d-043190b07632)
