### ISSUE TITLE
插件功能无法使用

### ISSUE THREAD

**Issue by LunaNorth** [siyuan-note/plugin-sample-vite-svelte#32]

**Comment by frostime** [comment]
不理解你的意思？这只是一个模板，本身没什么有实际意义的功能。

**Comment by LunaNorth** [comment]
> 不理解你的意思？这只是一个模板，本身没什么有实际意义的功能。

不好意思 ，前两天点错了仓库了 ，问题已经解决了 ，这个提问能删掉吗 ，麻烦您了！

**Comment by frostime** [comment]
> > 不理解你的意思？这只是一个模板，本身没什么有实际意义的功能。
> 
> 不好意思 ，前两天点错了仓库了 ，问题已经解决了 ，这个提问能删掉吗 ，麻烦您了！

无妨，close 掉就可以了。
