### ISSUE TITLE
自动打包功能貌似损坏了

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/plugin-sample-vite-svelte#34]
参见：https://github.com/zxhd863943427/siyuan-plugin-middle-search/actions/runs/10748477346

**Comment by frostime** [comment]
😥难顶

**Comment by frostime** [comment]
我看我这边打包还是正常的啊

https://github.com/siyuan-note/plugin-sample-vite-svelte/actions/runs/10749422865/job/29814301781

https://github.com/siyuan-note/plugin-sample-vite-svelte/releases/tag/v1.0.0

**Comment by frostime** [comment]
由于我这边测试了几个打包都没有问题，所以这个我就先关了，还有问题的话再说。

**Comment by zxhd863943427** [comment]
是我智障了，忘记打开GitHub setting的权限设置了
