### ISSUE TITLE
docker环境拉黑无效

### ISSUE THREAD

**Issue by seawin** [siyuan-note/plugin-sample-vite-svelte#35]
在名单中，但仍然显示

**Comment by frostime** [comment]
你好，在 `plugin.json` 文件中通过 `backend` 来声明黑名单是思源的工作，与模板没有直接关系。

如果你确定 `backend` 中有些字段无法生效，请到思源的 GitHub 仓库提交 issue：https://github.com/siyuan-note/siyuan。
