### ISSUE TITLE
Using the example with doOperations does not save the state

### ISSUE THREAD

**Issue by anarion80** [siyuan-note/plugin-sample-vite-svelte#36]
I'm trying to use the example and update a block in my plugin using the following example:

```javascript
element.outerHTML = genHtmlBlock({
        id: element.dataset.nodeId,
        index: element.dataset.index,
        updated: element.dataset.updated,
        content: escapeHtml(html)
    });

doOperations.push({
    id: element.dataset.nodeId,
    data: element.outerHTML,
    action: "update"
});
```

followed by `detail.protyle.getInstance().transaction(doOperations);`

I can see the changes reflected in the editor (block changed to HTML), but is is not saved - after page refresh or synchronization this update is not saved.

So is this not the correct way to update a block?

**Comment by frostime** [comment]
Hi, if you want to update the content of a block, it's best to use the kernel API `/api/block/updateBlock`: [API Documentation](https://github.com/siyuan-note/siyuan/blob/master/API.md#Update-a-block).

Directly modifying the `innerHTML` of the editor element (is called `protyle` in SiYuan) is strongly discouraged, as it can interfere with the SiYuan's event handlers. For more information, please refer to this guide: [Plugin Development Guide](https://docs.siyuan-note.club/en/guide/plugin/sy-plugin-dev-quick-start.html#protyle).

**Comment by anarion80** [comment]
Thanks. I have now moved to using `/api/block/updateBlock` and all is fine.
